# Generated by Django 3.1.2 on 2020-11-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201025_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
